services:
  app:
    env_file:
      - .env
    build: app
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - ./app:/code/
      - /code/node_modules
    depends_on:
      - db
    environment:
      PORT: ${SERVER_PORT}

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=cb-library
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "${DB_PORT}:${DB_PORT}"

volumes:
  postgres_data:
